### ISSUE TITLE
Space on left-bottom of RESULT resume

### ISSUE THREAD

**Issue by lokendarjangid** [IvanIsCoding/ResuLLMe#13]
-passed argument
![image](https://user-images.githubusercontent.com/57801045/232499749-c3bed1c0-cb88-4bf7-b7c1-0ef1aa08957c.png)

-passed pdf
[Profile.pdf](https://github.com/IvanIsCoding/ResuLLMe/files/11250730/Profile.pdf)

-result pdf 
[resume.pdf](https://github.com/IvanIsCoding/ResuLLMe/files/11250735/resume.pdf)

**Comment by lokendarjangid** [comment]
It is leaving more space on left side of builted resume

**Comment by IvanIsCoding** [comment]
Maybe it is a minor item we can fix with [paracol](https://www.ctan.org/pkg/paracol)? I’d encourage you to download the LaTeX source code and change the section where we define the columns, there could be an extra argument we can use

**Comment by lokendarjangid** [comment]
i tried but not able to solve. i have never used latex before so i am having defeculty to understand it.

when i used turning.json as input. two lines written in next page

![image](https://user-images.githubusercontent.com/57801045/232568592-d14c1c28-f44a-4904-a6eb-2e6c187d487f.png)

**Comment by IvanIsCoding** [comment]
That is not a bug. Résumés can be multiple pages long. That one is awkward because it is a really small second page, so trimming some information to fit in one page is better. But it is expected behaviour
