### ISSUE TITLE
Deployment using Docker on streamlit.io

### ISSUE THREAD

**Issue by SanhyewNg** [IvanIsCoding/ResuLLMe#25]
This app should be deployed using Docker to generate new resume pdf files.
But Streamlit Cloud does not directly support Docker.

How did you deploy on streamlit.io, Ivan? (https://resullme.streamlit.app/)

**Comment by IvanIsCoding** [comment]
I didn’t! `packages.txt` and `requirements.txt` are the only inputs that Streamlit cloud accepted. They control the packages installed.

The Docker container exists for the other way around. I copied the Ubuntu version from Streamlit cloud and slapped the `requirements.txt` and `packages.txt`. It’s not 100% equivalent but for this app it was close enough.

**Comment by SanhyewNg** [comment]
Oh, I see. Thanks for your kind reply.
