### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by IvanIsCoding** [IvanIsCoding/ResuLLMe#6]
It will help people run the app without LaTeX issues

**Comment by lokendarjangid** [comment]
can you assigne this to me

**Comment by lokendarjangid** [comment]
do you want to send container to hosting or just want to build container with the help of docker.

**Comment by IvanIsCoding** [comment]
Just build the container locally with the help of Docker

**Comment by lokendarjangid** [comment]
please review PR
